### ISSUE TITLE
Breaks 'Go to definition'

### ISSUE THREAD

**Issue by jgibo** [anacierdem/vscode-requirejs#76] opened 2021-08-31 08:35 UTC
Issue Type: <b>Bug</b>

As title says, it breaks it. Verified using extension bisect.

React 16 project using default create-react-app

Extension version: 0.1.33
VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:54:37.513Z)
OS version: Linux x64 5.13.10-200.fc34.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2379)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|15.32GB (3.69GB free)|
|Process Argv|--unity-launch --crash-reporter-id 51dd7a86-e7e5-457c-a049-8d74d61d00e8|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
bridge0723:30353136
vsdyn478:30356813
vscus224:30358039
vssid140:30358036

```

</details>

**Comment by anacierdem** [comment] 2021-08-31 08:36
This extension is not actively maintained. I suggest not using it until fixed.

**Comment by xmedeko** [comment] 2022-03-15 10:14
Duplicate of #69

**Closed as not planned** 2023-07-05 19:10 UTC
