### ISSUE TITLE
CommonJS style require does not work

### ISSUE THREAD

**Issue by michaelw85** [anacierdem/vscode-requirejs#19] opened 2017-07-08 12:26 UTC
```
define(function(require) {
    var moduleA = require('moduleA');
});
```

Trying to use the extension on moduleA returns not found.
I think this issue is caused by a bug in the part where it gets the list of modules + path from the define statement.

**Comment by anacierdem** [comment] 2017-07-08 14:31
This is a duplicate of #17. Moving this example over.

**Comment by anacierdem** [comment] 2017-07-08 14:33
Why dont you just use;

    require(['moduleA'], function(moduleA ) {

    });

**Comment by michaelw85** [comment] 2017-07-08 15:11
I think adding the dependency array in the describe makes it hard to read when the list becomes quite long. 

The app I work with uses this as a coding standard so fixing this issue will make this extension viable for me and I'm assuming I'm not the only one. 

It is a supported way to require statements so it would be good to support it.

**Comment by anacierdem** [comment] 2017-07-20 07:55
This is handled as a commonJS style require, instead of multiple statements.

**Comment by anacierdem** [comment] 2017-07-20 10:51
Published 0.0.33

**Closed by anacierdem** 2017-07-20 10:51 UTC
